#
# Apache server 2 para exponer archivos
#
#
# @autor: o.velez
# @fecha: 2022-09-24
#
# - ./conf:/usr/local/apache2/conf/
#
#
version: '3.3'

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - 80:80
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    environment:
      - TZ=America/Bogota