#
# Sonarqube is free software; you can redistribute it and/or
#
#
# @autor: o.velez
# @fecha: 2022-08-30
#
version: '3.3'

services:
  sonarqube:
    image: sonarqube:8.9.7-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    
    volumes:      
      - type: bind
        source: ./sonarqube/data
        target: /opt/sonarqube/data
      - type: bind
        source: ./sonarqube/extensions
        target: /opt/sonarqube/extensions
      - type: bind
        source: ./sonarqube/logs
        target: /opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    
    volumes:
      - type: bind
        source: ./postgresql/conf
        target: /var/lib/postgresql
      - type: bind
        source: ./postgresql/data
        target: /var/lib/postgresql/data

  init:
      image: bash
      privileged: true
      user: root
      volumes:
        - ./init.sh:/mnt/init.sh 
      command: ["sh", "-e", "/mnt/init.sh"]