##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## Login
@url=192.168.1.2:8080/lg_001_10/login
@username=admin
@password=yqZEQy97VC

@email=omargo@hotmail.com


###
# @name rdpAuth

post http://{{url}}
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
post http://{{url}}/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}

### solicitar una nueva clave
post http://{{url}}/lostPassword
Content-Type: application/x-www-form-urlencoded

email={{email}}