##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Consultas CIUDADES

@url=192.168.1.2:8080/lg_001_10/login
@username=admin
@password=BeY9JjUyVz
@servicio=127.0.0.1:8082/gs_001_10

###
# @name rdpAuth

post http://{{url}}
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
post http://{{url}}/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}


### listar todos
get http://{{servicio}}/
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### pagina 0 dos elementos y ordenado por nombre
get http://{{servicio}}/?page=0&size=2&sort=nombre,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i"
get http://{{servicio}}/nombre=i
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i", paginada y ordenada
get http://{{servicio}}/nombre=i?page=0&size=2&sort=nombre,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### buscar por indice
get http://{{servicio}}/10
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### crear
post http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{
    "nombre": "Quito",        
    "longitu": "-78.52495",
    "latitud": "-0.22985",
    "usuariPrograma": "manual"
}

### actualizar
put http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{
    "id": 10,
    "nombre": "Quito cambiado",        
    "longitu": "-78.52495",
    "latitud": "-0.22985",
    "usuariPrograma": "manual"
}

### eliminar por indice
delete http://{{servicio}}/110
Authorization: Bearer {{rdpAuth.response.headers.access-token}}