##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Consultas CLIENTES
@servicio=127.0.0.1:8081/si_001_00/informaciones
@username=AB:00:12:12:12:1A
@password=12341234

###
# @name rdpAuth

post http://127.0.0.1:8081/si_001_00/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
get http://127.0.0.1:8081/si_001_00/login/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}


### listar todos
get http://{{servicio}}/
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### pagina 0 dos elementos y ordenado por nombre
get http://{{servicio}}/?page=0&size=2&sort=nombre,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "-"
get http://{{servicio}}/nombre=-
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "0", paginada y ordenada
get http://{{servicio}}/nombre=0?page=0&size=2&sort=nombre,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### buscar por indice
get http://{{servicio}}/14
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### crear
post http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{
  "nombre": "api nuevo",
  "valor01": "https://www.youtube.com/watch?v=XsuE5Hky6xc",
  "valor02": null 
}

### actualizar
put http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{
  "idInformacion": 12,
   "nombre": "api nuevo45",
  "valor01": "https://www.youtube.com/watch?v=XsuE5Hky6xc",
  "valor02": "no vacio"
}

### eliminar por indice
delete http://{{servicio}}/13
Authorization: Bearer {{rdpAuth.response.headers.access-token}}