##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Consultas LOCALIZACIONES
@servicio=127.0.0.1:8080/si_001_00/localizaciones
@username=AB:00:12:12:12:1A
@password=12341234

###
# @name rdpAuth

post http://127.0.0.1:8080/si_001_00/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
get http://127.0.0.1:8080/si_001_00/login/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh_token}}


### listar todos
get http://{{servicio}}/
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### pagina 0 dos elementos y ordenado por nombre
get http://{{servicio}}/?page=0&size=4&sort=nombre,desc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i"
get http://{{servicio}}/nombre=A
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i", paginada y ordenada
get http://{{servicio}}/nombre=i?page=0&size=3&sort=nombre,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### buscar por indice
get http://{{servicio}}/2
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### crear
post http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{   
    "idCiudad": 2,
    "nombre": "Mall del rio 052",
    "latitud": "-2.860402",
    "longitud": "-79.041305" 
  }

### actualizar
put http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{
    "idLocalizacion": 7,
    "idCiudad": 2,
    "nombre": "Mall del rio 02",
    "latitud": "-2.860402",
    "longitud": "-79.041305"   
}
### eliminar por indice
delete http://{{servicio}}/3
Authorization: Bearer {{rdpAuth.response.headers.access-token}}