##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Consultas LOCALIZACIONES
@servicio=127.0.0.1:8080/si_001_00/monitores_alertas
@username=AB:00:12:12:12:1A
@password=12341234

###
# @name rdpAuth

post http://127.0.0.1:8080/si_001_00/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
get http://127.0.0.1:8080/si_001_00/login/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}


### listar todos
get http://{{servicio}}/
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### pagina 0 dos elementos y ordenado por nombre
get http://{{servicio}}/?page=0&size=4&sort=nombre,desc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i"
get http://{{servicio}}/nombre=a
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i", paginada y ordenada
get http://{{servicio}}/nombre=ale?page=0&size=1&sort=nombre,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### buscar por indice
get http://{{servicio}}/1
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### crear
post http://{{servicio}}/ 
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

 {   
    "idMonitor": 1,
    "nombre": "alerta enviada super nueva agenda",
    "descripcion": "sadfasdsa",
    "usuario": "manul",
    "usuarioFecha": "2022-10-14T04:09:23.000+00:00",
    "usuarioPrograma": "sadfs"
  }

### actualizar
put http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

 {   
    "idMonitorAlerta": 1,
    "idMonitor": 1,
    "nombre": "alerta enviada cambiada a uno",
    "descripcion": "sadfasdsa",
    "usuario": "manul",
    "usuarioFecha": "2022-10-14T04:09:23.000+00:00",
    "usuarioPrograma": "sadfs"
  }

### eliminar por indice
delete http://{{servicio}}/2
Authorization: Bearer {{rdpAuth.response.headers.access-token}}