##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Consultas LOCALIZACIONES
@servicio=127.0.0.1:8080/si_001_00/monitores_comandos
@username=AB:00:12:12:12:1A
@password=12341234

###
# @name rdpAuth

post http://127.0.0.1:8080/si_001_00/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
get http://127.0.0.1:8080/si_001_00/login/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}

  

### listar todos
get http://{{servicio}}/
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### pagina 0 dos elementos y ordenado por nombre
get http://{{servicio}}/?page=0&size=4&sort=elemento,desc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i"
get http://{{servicio}}/elemento=a
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por nombre que contenga la letra "i", paginada y ordenada
get http://{{servicio}}/elemento=8?page=0&size=1&sort=elemento,asc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### buscar por indice
get http://{{servicio}}/1
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### crear
post http://{{servicio}}/ 
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}
  
  {    
    "idMonitor": 1,
    "elemento": "12345678",
    "respuesta": "--",
    "descripcion": "kjlkj"
  }    


### actualizar
put http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

 {   
    "idMonitorComando": 2,
    "idMonitor": 1,
    "elemento": "8888",
    "respuesta": "--",
    "descripcion": "kjlkj"
  }

### eliminar por indice
delete http://{{servicio}}/1
Authorization: Bearer {{rdpAuth.response.headers.access-token}}