##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Revision de login
@username=admin  
@password=12341234
@email=omargo33@hotmail.com

###
# @name rdpAuth

post http://127.0.0.1:8080/gs_001_10/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
post http://127.0.0.1:8080/gs_001_10/login/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}

### enviar clave por correo
post http://127.0.0.1:8080/gs_001_10/login/lostPassword
Content-Type: application/x-www-form-urlencoded

email={{email}}
