###
### Docker compose para el despliegue de la aplicación
### @author o.velez@qapaq.io
###
version: '3'
services:
  springboot:
    image: qapaq/spring-boot:latest
    container_name: GS00100
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./target:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.2:3306/GS_001_00?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456s
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      ### - SPRING_JPA_SHOW_SQL=false
      - LOGGING_LEVEL_ROOT=warn
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=warn
      - LOGGING_LEVEL_COM_QAPAQ=warn
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE=warn
###
### Comando para ejecutar el docker compose y habilitar el puertos y red
### 
### docker-compose up -d
### docker-compose down
### docker-compose up
### docker stop GS00100
### docker start GS00100
### docker logs -f GS00100
### docker rm GS00100
###
### puede estar el cortafuegos activo en ubuntu      
### sudo ufw disable
###clear && mvn clean compile install