##
## o.velez@qapaq.io
##
## @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client
## 
## 
## Consultas modulos
@servicio=127.0.0.1:8080/gs_001_00/usuarios
@username=admin
@password=admin

###
# @name rdpAuth

post http://127.0.0.1:8080/gs_001_00/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### solicitar token refresh
get http://127.0.0.1:8080/gs_001_00/login/refresh
Authorization: Bearer {{rdpAuth.response.headers.refresh-token}}

### listar todos
get http://{{servicio}}/
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### pagina 0 dos elementos y ordenado por nombre
get http://{{servicio}}/?page=0&size=2&sort=nombre,desc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### id usuario
get http://{{servicio}}/15
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### id usuario
get http://{{servicio}}/nick=u089
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

### por indice que contenga la letra "i", paginada y ordenada
get http://{{servicio}}/nombres=velez?page=0&size=3&sort=nombre,desc
Authorization: Bearer {{rdpAuth.response.headers.access-token}}




### crear un nuevo modulo
POST http://{{servicio}}/ 
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{ 
    "idArchivo": null,
    "nick": "omar45-001",
    "nombre": "jk45-001",
    "apellido": "kljlkj",
    "usuarioPrograma": "rest-client"
}

### actualizar
put http://{{servicio}}/
Content-Type: application/json
Authorization: Bearer {{rdpAuth.response.headers.access-token}}

{
  "idUsuario": 45,
  "idArchivo": null,
    "nick": "u016",
    "nombre": "jk45-001",
    "apellido": "kljlkj",
    "usuarioPrograma": "rest-client"
}

### eliminar por indice
delete http://{{servicio}}/45
Authorization: Bearer {{rdpAuth.response.headers.access-token}}